CREATE OR REPLACE TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_GENRE_DETAIL (
    WEEK_ENDING_DATE DATE,
    YEAR INT,
    WEEK_NUM INT,
    GENRE_ID VARCHAR(255),
    GENRE_NAME VARCHAR,
    GENRE_LEVEL INT,
    COUNTRY_CODE VARCHAR(2),
    -- CURRENT, CATALOG, or TOTAL
    RELEASE_AGE VARCHAR(255),
    BU_ID VARCHAR(255),
    LABEL_NAME VARCHAR,
    -- METRICS
    STREAMING_TOTAL INT,
    ALBUM_EQUIVALENT FLOAT,
    PRODUCT_SALES FLOAT,
    SONG_SALE_EQUIVALENT FLOAT,
    STREAMING_EQUIVALENT FLOAT,
    -- MARKETSHARE
    ALBUM_EQUIVALENT_SHARE FLOAT,
    PRODUCT_SALES_SHARE FLOAT,
    SONG_SALE_EQUIVALENT_SHARE FLOAT,
    STREAMING_EQUIVALENT_SHARE FLOAT
);
