CREATE OR REPLACE TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_ALBUMS (
    MRELG_ID VARCHAR(255),
    -- For grouping releases by artist
    PRIMARY_ARTIST_ID VARCHAR(255),
    TITLE VARCHAR,
    DISPLAY_ARTIST VARCHAR,
    RELEASE_DATE DATE,
    COUNTRY_CODE VARCHAR(2),
    WEEK_ENDING_DATE DATE,
    IS_CURRENT BOOLEAN,
    STREAMING_TOTAL INT,
    ALBUM_EQUIVALENT FLOAT,
    PRODUCT_SALES FLOAT,
    SONG_SALE_EQUIVALENT FLOAT,
    STREAMING_EQUIVALENT FLOAT,
    LEVEL_1_DISTRIBUTOR VARCHAR,
    LEVEL_1_DISTRIBUTOR_BU_ID VARCHAR,
    LEVEL_2_DISTRIBUTOR VARCHAR,
    LEVEL_2_DISTRIBUTOR_BU_ID VARCHAR,
    LEVEL_3_DISTRIBUTOR VARCHAR,
    LEVEL_3_DISTRIBUTOR_BU_ID VARCHAR
);