CREATE OR REPLACE TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_ISRCS (
    MR_ID STRING,
    ISRC STRING,
    COUNTRY_CODE STRING,
    LEVEL_1_DISTRIBUTOR STRING,
    LEVEL_2_DISTRIBUTOR STRING,
    LEVEL_3_DISTRIBUTOR STRING,
    RELEASE_DATE DATE,
    IS_CURRENT BOOLEAN,
    PERCENT_OWNED FLOAT
);
