CREATE OR REPLACE TABLE CURRENT_DEV.DATA.MARKETSHARE_FORECASTS (
    WEEK_ENDING_DATE DATE,
    YEAR INT,
    WEEK_NUM INT,
    COUNTRY_CODE STRING,
    LABEL_NAME STRING,
    RELEASE_AGE STRING,
    STREAMING_TOTAL INT,
    ALBUM_EQUIVALENT FLOAT,
    PRODUCT_SALES FLOAT,
    SONG_SALE_EQUIVALENT FLOAT,
    STREAMING_EQUIVALENT FLOAT,
    ALBUM_EQUIVALENT_SHARE FLOAT,
    PRODUCT_SALES_SHARE FLOAT,
    SONG_SALE_EQUIVALENT_SHARE FLOAT,
    STREAMING_EQUIVALENT_SHARE FLOAT,
    FORECAST BOOLEAN
);