CREATE OR REPLACE TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_ICPNS (
    MP_ID STRING,
    ICPN STRING,
    COUNTRY_CODE STRING,
    LEVEL_1_DISTRIBUTOR STRING,
    LEVEL_1_DISTRIBUTOR_BU_ID STRING,
    LEVEL_2_DISTRIBUTOR STRING,
    LEVEL_2_DISTRIBUTOR_BU_ID STRING,
    LEVEL_3_DISTRIBUTOR STRING,
    LEVEL_3_DISTRIBUTOR_BU_ID STRING,
    RELEASE_DATE DATE,
    IS_CURRENT BOOLEAN,
    PERCENT_OWNED FLOAT
);
