CREATE OR REPLACE TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY (
    WEEK_ENDING_DATE STRING,
    YEAR INT,
    WEEK_NUM INT,
    COUNTRY_CODE STRING,
    -- CURRENT, CATALOG, or TOTAL
    RELEASE_AGE STRING,
    BU_ID STRING,
    LABEL_NAME STRING,
    -- METRICS
    STREAMING_TOTAL INT,
    ALBUM_EQUIVALENT FLOAT,
    PRODUCT_SALES FLOAT,
    SONG_SALE_EQUIVALENT FLOAT,
    STREAMING_EQUIVALENT FLOAT,
    -- MARKETSHARE
    ALBUM_EQUIVALENT_SHARE FLOAT,
    PRODUCT_SALES_SHARE FLOAT,
    SONG_SALE_EQUIVALENT_SHARE FLOAT,
    STREAMING_EQUIVALENT_SHARE FLOAT
);
