CREATE OR REPLACE TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_ARTISTS (
    ARTIST_ID VARCHAR(255),
    -- For grouping releases by artist
    ARTIST_NAME VARCHAR,
    COUNTRY_CODE VARCHAR(2),
    WEEK_ENDING_DATE DATE,
    IS_CURRENT BOOLEAN,
    STREAMING_TOTAL INT,
    ALBUM_EQUIVALENT FLOAT,
    PRODUCT_SALES FLOAT,
    SONG_SALE_EQUIVALENT FLOAT,
    STREAMING_EQUIVALENT FLOAT,
    LEVEL_1_DISTRIBUTOR VARCHAR,
    LEVEL_1_DISTRIBUTOR_BU_ID VARCHAR,
    LEVEL_2_DISTRIBUTOR VARCHAR,
    LEVEL_2_DISTRIBUTOR_BU_ID VARCHAR,
    LEVEL_3_DISTRIBUTOR VARCHAR,
    LEVEL_3_DISTRIBUTOR_BU_ID VARCHAR,
    CONSTRAINT PK_MARKETSHARE_WEEKLY_ARTISTS PRIMARY KEY (
        ARTIST_ID,
        COUNTRY_CODE,
        WEEK_ENDING_DATE,
        IS_CURRENT,
        LEVEL_1_DISTRIBUTOR_BU_ID,
        LEVEL_2_DISTRIBUTOR_BU_ID,
        LEVEL_3_DISTRIBUTOR_BU_ID
    )
);
