-- Idempotent migration: add BU_ID columns to all marketshare tables.
-- Safe to run on every pipeline execution. Snowflake ignores ADD COLUMN IF NOT EXISTS when the column already exists.
-- run_migrations() splits this file on the statement separator character,
-- so that character must never appear inside a comment.

-- MARKETSHARE_MAP_LABEL_HIERARCHY: add per-level distributor BU_ID columns
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_LABEL_HIERARCHY ADD COLUMN IF NOT EXISTS LEVEL_1_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_LABEL_HIERARCHY ADD COLUMN IF NOT EXISTS LEVEL_2_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_LABEL_HIERARCHY ADD COLUMN IF NOT EXISTS LEVEL_3_DISTRIBUTOR_BU_ID STRING;

-- MARKETSHARE_MAP_ICPNS: add per-level distributor BU_ID columns
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_ICPNS ADD COLUMN IF NOT EXISTS LEVEL_1_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_ICPNS ADD COLUMN IF NOT EXISTS LEVEL_2_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_ICPNS ADD COLUMN IF NOT EXISTS LEVEL_3_DISTRIBUTOR_BU_ID STRING;

-- MARKETSHARE_MAP_ISRCS: add per-level distributor BU_ID columns
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_ISRCS ADD COLUMN IF NOT EXISTS LEVEL_1_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_ISRCS ADD COLUMN IF NOT EXISTS LEVEL_2_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_MAP_ISRCS ADD COLUMN IF NOT EXISTS LEVEL_3_DISTRIBUTOR_BU_ID STRING;

-- MARKETSHARE_WEEKLY: add single BU_ID column
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY ADD COLUMN IF NOT EXISTS BU_ID STRING;

-- MARKETSHARE_YTD: add single BU_ID column
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_YTD ADD COLUMN IF NOT EXISTS BU_ID STRING;

-- MARKETSHARE_FORECASTS: add single BU_ID column
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_FORECASTS ADD COLUMN IF NOT EXISTS BU_ID STRING;

-- MARKETSHARE_FORECASTS_WEEKLY: add single BU_ID column
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_FORECASTS_WEEKLY ADD COLUMN IF NOT EXISTS BU_ID STRING;

-- MARKETSHARE_WEEKLY_ALBUMS: add per-level distributor BU_ID columns
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_ALBUMS ADD COLUMN IF NOT EXISTS LEVEL_1_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_ALBUMS ADD COLUMN IF NOT EXISTS LEVEL_2_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_ALBUMS ADD COLUMN IF NOT EXISTS LEVEL_3_DISTRIBUTOR_BU_ID STRING;

-- MARKETSHARE_WEEKLY_ARTISTS: add per-level distributor BU_ID columns
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_ARTISTS ADD COLUMN IF NOT EXISTS LEVEL_1_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_ARTISTS ADD COLUMN IF NOT EXISTS LEVEL_2_DISTRIBUTOR_BU_ID STRING;
ALTER TABLE CURRENT_DEV.DATA.MARKETSHARE_WEEKLY_ARTISTS ADD COLUMN IF NOT EXISTS LEVEL_3_DISTRIBUTOR_BU_ID STRING;
